name: Deploy to AWS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::204754236937:role/terrateamAccessRole
          aws-region: eu-west-2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::204754236937:role/terrateamAccessRole
          aws-region: eu-west-2
          debug: true  # optional: to see more detailed logs
      - name: Deploy to AWS
        run: |
          aws s3 cp ./test/ s3://github-test-bucket-9089/ --recursive
# Note the bucket must exist
